@extends('layouts.admin')

@section('title', 'Lịch sử soát vé - MovieMate')
@section('page-title', 'Lịch sử soát vé')

@section('content')
<div class="space-y-6">
    <header><h1 class="admin-page-title">Lịch sử soát vé</h1><p class="admin-page-subtitle">Theo dõi các lần quét vé thành công, quét trùng và các lần bị từ chối.</p></header>
    <form method="GET" class="cinema-card grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
        <label class="text-sm font-bold">Mã đặt vé<input class="cinema-input mt-1" name="booking_code" value="{{ $filters['booking_code'] ?? '' }}"></label><label class="text-sm font-bold">Phim<input class="cinema-input mt-1" name="movie" value="{{ $filters['movie'] ?? '' }}"></label><label class="text-sm font-bold">Phòng<input class="cinema-input mt-1" name="room" value="{{ $filters['room'] ?? '' }}"></label><label class="text-sm font-bold">ID suất chiếu<input class="cinema-input mt-1" type="number" min="1" name="showtime_id" value="{{ $filters['showtime_id'] ?? '' }}"></label>
        <label class="text-sm font-bold">Nhân viên<input class="cinema-input mt-1" name="actor" value="{{ $filters['actor'] ?? '' }}"></label><label class="text-sm font-bold">Kết quả<select class="cinema-input mt-1" name="result"><option value="">Tất cả</option>@foreach(\App\Models\TicketCheckinEvent::RESULTS as $result)<option value="{{ $result }}" @selected(($filters['result'] ?? '') === $result)>{{ \App\Support\StatusLabel::for('ticket_checkin', $result) }}</option>@endforeach</select></label><label class="text-sm font-bold">Lý do<input class="cinema-input mt-1" name="reason" value="{{ $filters['reason'] ?? '' }}"></label>
        <label class="text-sm font-bold">Từ ngày<input class="cinema-input mt-1" type="date" name="scanned_from" value="{{ $filters['scanned_from'] ?? '' }}"></label><label class="text-sm font-bold">Đến ngày<input class="cinema-input mt-1" type="date" name="scanned_to" value="{{ $filters['scanned_to'] ?? '' }}"></label>
        <label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="duplicates_only" value="yes" @checked(($filters['duplicates_only'] ?? '') === 'yes')>Chỉ quét trùng</label><label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="rejected_only" value="yes" @checked(($filters['rejected_only'] ?? '') === 'yes')>Chỉ bị từ chối</label>
        <div class="flex items-end gap-2 xl:col-span-4"><button class="btn-primary" type="submit"><i class="ph ph-funnel"></i>Lọc</button><a class="btn-secondary" href="{{ route('admin.ticket-checkins.index') }}">Xóa lọc</a></div>
    </form>
    <section class="cinema-card overflow-hidden"><div class="overflow-x-auto"><table class="admin-table min-w-[82rem]"><thead><tr><th>Mã đặt vé</th><th>Phim</th><th>Suất chiếu</th><th>Phòng</th><th>Ghế</th><th>Nhân viên</th><th>Kết quả</th><th>Lý do</th><th>Thời gian quét</th><th>Thao tác</th></tr></thead><tbody>
        @forelse($events as $event)<tr><td class="font-bold text-brand-start">{{ $event->booking?->booking_code ?? '—' }}</td><td>{{ $event->showtime?->movie?->title ?? '—' }}</td><td>{{ $event->showtime?->show_date?->format('d/m/Y') }} {{ $event->showtime?->show_time ? \Carbon\Carbon::parse($event->showtime->show_time)->format('H:i') : '' }}</td><td>{{ $event->showtime?->room?->code ?? '—' }}</td><td>{{ $event->booking?->seat_codes ?: '—' }}</td><td>{{ $event->actor?->name ?? 'Tài khoản không còn khả dụng' }}<span class="block text-xs app-muted">{{ \App\Support\StatusLabel::for('role', $event->actor_role_snapshot) }}</span></td><td><span class="status-badge {{ $event->result === 'accepted' ? 'bg-success/10 text-success' : ($event->result === 'already_used' ? 'bg-warning/10 text-warning' : 'bg-error/10 text-error') }}">{{ \App\Support\StatusLabel::for('ticket_checkin', $event->result) }}</span></td><td>{{ \App\Support\TicketCheckinPresentation::reason($event->reason_code) }}</td><td>{{ $event->scanned_at?->format('d/m/Y H:i:s') }}</td><td><a class="font-bold text-brand-start" href="{{ route('admin.ticket-checkins.show', $event) }}">Chi tiết</a></td></tr>
        @empty<tr><td colspan="10" class="py-12 text-center app-muted">Chưa có lịch sử soát vé phù hợp.</td></tr>@endforelse
    </tbody></table></div>@if($events->hasPages())<div class="border-t app-border p-4">{{ $events->links() }}</div>@endif</section>
</div>
@endsection
