@extends('layouts.admin')

@section('title', 'Chi tiết soát vé - MovieMate')
@section('page-title', 'Chi tiết lịch sử soát vé')

@section('content')
<div class="space-y-6"><header><a class="mb-3 inline-flex items-center gap-2 font-bold text-brand-start" href="{{ route('admin.ticket-checkins.index') }}"><i class="ph ph-arrow-left"></i>Lịch sử soát vé</a><h1 class="admin-page-title">{{ $booking?->booking_code ?? 'Sự kiện #'.$event->id }}</h1><p class="admin-page-subtitle">Bản ghi chỉ đọc, không chứa token hoặc URL QR.</p></header>
    <section class="cinema-card p-6"><dl class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><dt class="app-muted">Kết quả</dt><dd class="font-bold">{{ \App\Support\StatusLabel::for('ticket_checkin', $event->result) }}</dd></div><div><dt class="app-muted">Lý do</dt><dd class="font-bold">{{ \App\Support\TicketCheckinPresentation::reason($event->reason_code) }}</dd></div><div><dt class="app-muted">Thời gian quét</dt><dd class="font-bold">{{ $event->scanned_at?->format('d/m/Y H:i:s') }}</dd></div><div><dt class="app-muted">Request ID</dt><dd class="break-all font-mono text-xs">{{ $event->request_id ?? '—' }}</dd></div><div><dt class="app-muted">Nhân viên</dt><dd class="font-bold">{{ $event->actor?->name ?? 'Tài khoản không còn khả dụng' }}</dd></div><div><dt class="app-muted">Vai trò lúc quét</dt><dd class="font-bold">{{ \App\Support\StatusLabel::for('role', $event->actor_role_snapshot) }}</dd></div><div><dt class="app-muted">Trình duyệt an toàn</dt><dd class="font-bold">{{ $event->user_agent_summary ?? 'Không xác định' }}</dd></div><div><dt class="app-muted">Khách hàng</dt><dd class="font-bold">{{ $customerMasked }}</dd></div></dl></section>
    <section class="cinema-card p-6"><h2 class="text-xl font-extrabold app-heading">Vé và suất chiếu</h2><dl class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><dt class="app-muted">Phim</dt><dd class="font-bold">{{ $event->showtime?->movie?->title ?? '—' }}</dd></div><div><dt class="app-muted">Suất chiếu</dt><dd class="font-bold">{{ $event->showtime?->show_date?->format('d/m/Y') ?? '—' }} {{ $event->showtime?->show_time ? \Carbon\Carbon::parse($event->showtime->show_time)->format('H:i') : '' }}</dd></div><div><dt class="app-muted">Phòng</dt><dd class="font-bold">{{ $event->showtime?->room?->code ?? '—' }}</dd></div><div><dt class="app-muted">Ghế</dt><dd class="font-bold">{{ $seatGroups->pluck('label')->join(', ') ?: '—' }}</dd></div></dl></section>
    @can('activity_logs.view')<section class="cinema-card overflow-hidden"><div class="border-b app-border p-6"><h2 class="text-xl font-extrabold app-heading">Nhật ký cùng request</h2></div><div class="overflow-x-auto"><table class="admin-table"><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Hành động</th></tr></thead><tbody>@forelse($activity as $log)<tr><td>{{ $log->created_at?->format('d/m/Y H:i:s') }}</td><td>{{ $log->actor?->name ?? 'Hệ thống' }}</td><td>{{ $log->action }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center app-muted">Không có ActivityLogger tương ứng.</td></tr>@endforelse</tbody></table></div></section>@endcan
</div>
@endsection
