@extends('layouts.admin')
@section('title', $discount->exists ? 'Sửa mã giảm giá' : 'Thêm mã giảm giá')
@section('page-title', $discount->exists ? 'Sửa mã giảm giá' : 'Thêm mã giảm giá')
@section('content')
<form method="POST" action="{{ $discount->exists ? route('admin.discounts.update', $discount) : route('admin.discounts.store') }}" class="admin-form-card max-w-5xl">@csrf @if($discount->exists)@method('PUT')@endif
<div class="grid gap-5 md:grid-cols-2">
<div><label class="admin-label">Mã</label><input name="code" value="{{ old('code', $discount->code) }}" class="admin-input uppercase" required></div><div><label class="admin-label">Tên chương trình</label><input name="name" value="{{ old('name', $discount->name) }}" class="admin-input" required></div>
<div><label class="admin-label">Loại giảm</label><select name="discount_type" class="admin-input"><option value="fixed" @selected(old('discount_type',$discount->discount_type)==='fixed')>Số tiền cố định</option><option value="percent" @selected(old('discount_type',$discount->discount_type)==='percent')>Phần trăm</option></select></div><div><label class="admin-label">Giá trị</label><input type="number" min="1" name="discount_value" value="{{ old('discount_value',$discount->discount_value) }}" class="admin-input" required></div>
<div><label class="admin-label">Giảm tối đa (VNĐ)</label><input type="number" min="0" name="maximum_discount_amount" value="{{ old('maximum_discount_amount',$discount->maximum_discount_amount) }}" class="admin-input"></div><div><label class="admin-label">Đơn tối thiểu (VNĐ)</label><input type="number" min="0" name="minimum_order_amount" value="{{ old('minimum_order_amount',$discount->minimum_order_amount ?? 0) }}" class="admin-input" required></div>
<div><label class="admin-label">Bắt đầu</label><input type="datetime-local" name="starts_at" value="{{ old('starts_at',$discount->starts_at?->format('Y-m-d\TH:i')) }}" class="admin-input"></div><div><label class="admin-label">Kết thúc</label><input type="datetime-local" name="ends_at" value="{{ old('ends_at',$discount->ends_at?->format('Y-m-d\TH:i')) }}" class="admin-input"></div>
<div><label class="admin-label">Tổng lượt</label><input type="number" min="1" name="total_quota" value="{{ old('total_quota',$discount->total_quota) }}" class="admin-input"></div><div><label class="admin-label">Lượt mỗi khách</label><input type="number" min="1" name="per_user_quota" value="{{ old('per_user_quota',$discount->per_user_quota) }}" class="admin-input"></div>
<div><label class="admin-label">Ưu tiên</label><input type="number" name="priority" value="{{ old('priority',$discount->priority ?? 0) }}" class="admin-input" required></div><div><label class="admin-label">Trạng thái</label><select name="is_active" class="admin-input"><option value="1" @selected(old('is_active',$discount->is_active ?? true))>Đang áp dụng</option><option value="0" @selected(!old('is_active',$discount->is_active ?? true))>Tạm ngừng</option></select></div>
<fieldset class="md:col-span-2"><legend class="admin-label">{{ $canCreateGlobalPromotion ? 'Chi nhánh (để trống = toàn hệ thống)' : 'Chi nhánh áp dụng (bắt buộc)' }}</legend><div class="grid gap-2 sm:grid-cols-2">@foreach($cinemas as $cinema)<label class="flex gap-2"><input type="checkbox" name="cinema_ids[]" value="{{ $cinema->id }}" @checked(in_array($cinema->id, old('cinema_ids',$discount->cinemas?->pluck('id')->all() ?? [])))>{{ $cinema->name }}</label>@endforeach</div>@unless($canCreateGlobalPromotion)<p class="mt-2 text-xs app-muted">Manager chỉ có thể lưu mã cho chi nhánh đang chọn; phạm vi toàn hệ thống chỉ do Admin quản lý.</p>@endunless</fieldset>
<div class="md:col-span-2 flex flex-wrap gap-4">@foreach(['registered_users_only'=>'Chỉ khách đăng nhập','first_order_only'=>'Chỉ đơn đầu tiên','can_combine'=>'Cho phép kết hợp'] as $field=>$label)<label class="flex gap-2"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$discount->{$field}))>{{ $label }}</label>@endforeach</div>
<div class="md:col-span-2"><label class="admin-label">Mô tả</label><textarea name="description" class="admin-input" rows="3">{{ old('description',$discount->description) }}</textarea></div></div>
<x-validation-summary class="mt-5" :errors="$errors"/><div class="mt-6 flex gap-3"><button class="admin-btn-primary">Lưu</button><a class="admin-btn-secondary" href="{{ route('admin.discounts.index') }}">Quay lại</a></div></form>
@if($discount->exists && !$discount->archived_at)<form method="POST" action="{{ route('admin.discounts.archive',$discount) }}" class="mx-auto mt-4 max-w-5xl">@csrf @method('PATCH')<button class="admin-btn-secondary">Lưu trữ mã</button></form>@endif
@endsection
