@extends('layouts.admin')
@section('title', ($rule->exists ? 'Sửa' : 'Tạo').' quy tắc giá - MovieMate')
@section('page-title', $rule->exists ? 'Sửa quy tắc giá' : 'Tạo quy tắc giá')
@section('content')
<form method="POST" action="{{ $rule->exists ? route('admin.pricing-rules.update', $rule) : route('admin.pricing-rules.store') }}" class="app-card mx-auto max-w-5xl space-y-5 rounded-2xl border app-border p-6">@csrf @if($rule->exists)@method('PATCH')@endif
<div><label class="cinema-label">Tên quy tắc</label><input name="name" value="{{ old('name',$rule->name) }}" class="cinema-input" required>@error('name')<p class="text-error">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="cinema-label">Loại</label><select name="rule_type" class="cinema-input">@foreach(\App\Models\CinemaPricingRule::TYPES as $type)<option value="{{ $type }}" @selected(old('rule_type',$rule->rule_type)===$type)>{{ $type }}</option>@endforeach</select></div><div><label class="cinema-label">Chi nhánh</label><select name="cinema_id" class="cinema-input"><option value="">Toàn hệ thống (chỉ Admin)</option>@foreach($cinemas as $cinema)<option value="{{ $cinema->id }}" @selected(old('cinema_id',$rule->cinema_id)==$cinema->id)>{{ $cinema->name }}</option>@endforeach</select>@error('cinema_id')<p class="text-error">{{ $message }}</p>@enderror</div><div><label class="cinema-label">Phòng</label><select name="room_id" class="cinema-input"><option value="">Mọi phòng</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(old('room_id',$rule->room_id)==$room->id)>{{ $room->code }} · {{ $room->name }}</option>@endforeach</select>@error('room_id')<p class="text-error">{{ $message }}</p>@enderror</div></div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="cinema-label">Loại ghế</label><select name="seat_type" class="cinema-input"><option value="">Không giới hạn</option>@foreach(\App\Models\Seat::TYPES as $type)<option value="{{ $type }}" @selected(old('seat_type',$rule->seat_type)===$type)>{{ $type }}</option>@endforeach</select></div><div><label class="cinema-label">Loại phòng</label><select name="room_type" class="cinema-input"><option value="">Không giới hạn</option>@foreach(['2D','3D','IMAX'] as $type)<option value="{{ $type }}" @selected(old('room_type',$rule->room_type)===$type)>{{ $type }}</option>@endforeach</select></div><div><label class="cinema-label">Mức giá/phụ thu (VNĐ)</label><input type="number" name="amount_vnd" value="{{ old('amount_vnd',$rule->amount_vnd ?? 0) }}" class="cinema-input" required>@error('amount_vnd')<p class="text-error">{{ $message }}</p>@enderror</div></div>
<div class="grid gap-4 md:grid-cols-4"><div><label class="cinema-label">Từ ngày đặc biệt</label><input type="date" name="date_start" value="{{ old('date_start',$rule->date_start?->format('Y-m-d')) }}" class="cinema-input"></div><div><label class="cinema-label">Đến ngày</label><input type="date" name="date_end" value="{{ old('date_end',$rule->date_end?->format('Y-m-d')) }}" class="cinema-input"></div><div><label class="cinema-label">Khung giờ từ</label><input type="time" name="time_start" value="{{ old('time_start',$rule->time_start ? substr($rule->time_start,0,5) : '') }}" class="cinema-input"></div><div><label class="cinema-label">Đến</label><input type="time" name="time_end" value="{{ old('time_end',$rule->time_end ? substr($rule->time_end,0,5) : '') }}" class="cinema-input"></div></div>
<fieldset><legend class="cinema-label">Ngày trong tuần</legend><div class="flex flex-wrap gap-3">@foreach([1=>'Thứ hai',2=>'Thứ ba',3=>'Thứ tư',4=>'Thứ năm',5=>'Thứ sáu',6=>'Thứ bảy',7=>'Chủ nhật'] as $day=>$label)<label><input type="checkbox" name="days_of_week[]" value="{{ $day }}" @checked(in_array($day,old('days_of_week',$rule->days_of_week??[])))> {{ $label }}</label>@endforeach</div></fieldset>
<div class="grid gap-4 md:grid-cols-4"><div><label class="cinema-label">Ưu tiên</label><input type="number" name="priority" value="{{ old('priority',$rule->priority??0) }}" class="cinema-input"></div><div><label class="cinema-label">Hiệu lực từ</label><input type="datetime-local" name="starts_at" value="{{ old('starts_at',$rule->starts_at?->format('Y-m-d\TH:i')) }}" class="cinema-input"></div><div><label class="cinema-label">Hiệu lực đến</label><input type="datetime-local" name="ends_at" value="{{ old('ends_at',$rule->ends_at?->format('Y-m-d\TH:i')) }}" class="cinema-input"></div><div><label class="cinema-label">Trạng thái</label><select name="status" class="cinema-input"><option value="active" @selected(old('status',$rule->status??'active')==='active')>Đang áp dụng</option><option value="inactive" @selected(old('status',$rule->status)==='inactive')>Tạm ngừng</option></select></div></div>
<label class="block"><input type="checkbox" name="stacks_with_weekend" value="1" @checked(old('stacks_with_weekend',$rule->stacks_with_weekend))> Ngày đặc biệt được cộng thêm phụ thu cuối tuần</label>
<div class="flex gap-3"><button class="admin-btn-primary">{{ $rule->exists ? 'Cập nhật' : 'Tạo quy tắc' }}</button><a href="{{ route('admin.pricing-rules.index') }}" class="admin-btn-secondary">Quay lại</a></div></form>
@if($rule->exists)<form method="POST" action="{{ route('admin.pricing-rules.status',$rule) }}" class="mx-auto mt-4 max-w-5xl">@csrf<input type="hidden" name="status" value="{{ $rule->status==='active'?'inactive':'active' }}"><button class="admin-btn-secondary">{{ $rule->status==='active'?'Tạm ngừng':'Kích hoạt' }}</button></form>@endif
@endsection
