@extends('layouts.admin')
@section('title', $layoutTemplate->name)
@section('content')
<div class="space-y-6"><div class="flex justify-between"><div><h1 class="text-2xl font-bold">{{ $layoutTemplate->name }}</h1><p class="app-muted">{{ $layoutTemplate->code }} · {{ $roomTypeName ?: 'Mọi loại phòng' }} · {{ $layoutTemplate->status_label }} · {{ $layoutTemplate->rows }} × {{ $layoutTemplate->columns }}</p></div><div class="flex gap-2">@can('layout_templates.manage')
@if($layoutTemplate->status !== 'archived')<a class="btn-secondary" href="{{ route('admin.layout-templates.edit',$layoutTemplate) }}">Chỉnh sửa</a>@endif
@if($layoutTemplate->status === 'draft')<form method="POST" action="{{ route('admin.layout-templates.activate',$layoutTemplate) }}">@csrf<button class="btn-primary">Đưa vào sử dụng</button></form>@endif
@if($layoutTemplate->status !== 'archived')<form method="POST" action="{{ route('admin.layout-templates.archive',$layoutTemplate) }}">@csrf<button class="btn-secondary">Lưu trữ</button></form>@endif @endcan</div></div>
<div class="app-card p-5 overflow-auto"><div class="text-center py-2 rounded bg-slate-700 mb-4">MÀN HÌNH</div><div class="grid gap-1 mx-auto" style="grid-template-columns:repeat({{ $layoutTemplate->columns }},2.7rem);width:max-content">@php($byCoordinate=$layoutTemplate->cells->keyBy(fn($c)=>$c->x_position.':'.$c->y_position)) @for($y=1;$y<=$layoutTemplate->rows;$y++) @for($x=1;$x<=$layoutTemplate->columns;$x++) @php($cell=$byCoordinate->get($x.':'.$y))<div class="h-10 rounded flex items-center justify-center text-xs {{ !$cell ? 'border app-border' : ($cell->cell_type==='aisle'?'bg-slate-700':($cell->seat_type==='vip'?'bg-amber-600':($cell->seat_type==='couple'?'bg-pink-600':'bg-indigo-600'))) }}">{{ $cell?->cell_type === 'aisle' ? '—' : $cell?->seat_label }}</div>@endfor @endfor</div></div>
<div class="app-card p-5"><h2 class="font-semibold mb-3">Lịch sử áp dụng</h2>@forelse($usages as $layout)<div class="py-2 border-b app-border">{{ $layout->display_name }} · {{ $layout->room->cinema->name }} / {{ $layout->room->name }} · {{ $layout->status_label }}</div>@empty<p class="app-muted">Mẫu chưa được áp dụng.</p>@endforelse</div>{{ $usages->links() }}</div>
@endsection
